### ISSUE TITLE
SMS select SIM card

### ISSUE THREAD

**Issue by raresn** [distriqt/ANE-Message#53]
Hey guys,
We are in the position where we have 2 sim cards inserted in our phone and we want to choose which one we use when sending.
Do you think you can help us out?

Thank you,
Rares

**Comment by raresn** [comment]
Hey,
Found one thing that is missing:
If we are using two sims, we need the know the Subscription ID for the received message (the sim that recevied the message)
Is it there and we just missed it? or needs to be added?
Thank you!

**Comment by marchbold** [comment]
Hi, Can you log this as a new feature request and we will look into it.
