### ISSUE TITLE
Subscription ID - get the ID for the sim tat recevied the message

### ISSUE THREAD

**Issue by raresn** [distriqt/ANE-Message#55]
Hey,
Found one thing that is missing:
If we are using two sims, we need the know the Subscription ID for the received message (the sim that recevied the message)
Thank you!

**Comment by marchbold** [comment]
It's not a simple task currently to retrieve the subscription id from an sms. 

We have found one method, appears to be undocumented, so may not work across all devices:

https://www.dropbox.com/s/oqurcextfnplgm7/com.distriqt.Message.v6.1.016.zip?dl=0

Should find a `subscriptionId` property on the `SMS` object received.

Let me know how it goes.

**Comment by raresn** [comment]
It works! Thank you for such a fast update!
Is it ok if we use this version in production?

**Comment by marchbold** [comment]
Excellent! 

I'll push this into production today, just be aware it's not officially documented so may not work on all devices. We haven't had any issues in our tests though.
