### ISSUE TITLE
Body not present

### ISSUE THREAD

**Issue by Voltigeuse** [distriqt/ANE-Message#59]
My app for Android take a picture and join it by mail. The email is well done but without any body

![image](https://user-images.githubusercontent.com/8626305/99884900-a947b280-2c31-11eb-8baf-9976518f975d.png)

body is well filled as in my trace 
![image](https://user-images.githubusercontent.com/8626305/99884928-c2e8fa00-2c31-11eb-98b9-f722240247e3.png)

Do you have any idea of the problem ?

Framework Flash Builder 4.7
SDK air 33.1.1.300
Samsung Galaxy S7 SM-G930F
Android 8.0.0

**Comment by marchbold** [comment]
What email client are you using, as we don't control the client all we can do is pass the data to the client? What the email client application does with the data is dependent on the developers of the client. 

Have you tried with the html flag to false, it could be that it doesn't accept html content.

**Comment by Voltigeuse** [comment]
I used Outlook I will try with gmail. 
I don't know how to put html flag to false, where have I to put this ?

**Comment by Voltigeuse** [comment]
In fact with gmail it'is working.
Can you still tell me how to put html flag to false and where have I to put this ?
Thanks a lot

**Comment by marchbold** [comment]
With the sendMailWithOptions function it is the 7th parameter, `isHTML`, a boolean value, "if true the body string is rendered as html":

https://docs.airnativeextensions.com/asdocs/message/com/distriqt/extension/message/Message.html#sendMailWithOptions()

**Comment by Voltigeuse** [comment]
Ok thank you
