### ISSUE TITLE
Choose Email Client with Message.service.sendMailWithOptions?

### ISSUE THREAD

**Issue by zishani** [distriqt/ANE-Message#62]
Is it possible to get the user to pick which email client they want to use when using Message.service.sendMailWithOptions?

E.g a user has the Outlook app and Mail app installed on their iPad.

If we call Message.service.sendMailWithOptions with useChooser set to true - it still opens the Mail app by default.

Is there a way to give users the option to select if they want to send mail with Outlook or Mail?

Thanks

**Comment by marchbold** [comment]
No, this is not possible on iOS and is completely controlled by the user and what they have configured their default settings to be.

**Comment by zishani** [comment]
OK - that's what I thought - but thanks for confirming!
________________________________
